SELECT TOP (1000) [CompanyName]
      ,[BuyerVat]
      ,[PCICode]
      ,[ProcedureRequestID]
      ,[Reference]
      ,[PPI]
      ,[BuyerDossierID]
      ,[ProcedureRequestName]
      ,[ProcedureRequestDescription2]
      ,[ProfileDocUniqueName]
      ,[PhaseName]
      ,[RequestOnlinePublishingDate]
      ,[Fecha Publicación]
      ,[Fecha Publicacion fase planeacion precalficacion]
      ,[Fecha Publicacion fase seleccion precalficacion]
      ,[Fecha de Menifestacion de Interes]
      ,[Fecha de publicacion de la fase borrador]
      ,[Fecha de Publicacion de la fase Seleccion]
      ,[BasePrice]
      ,[SubmissionUser]
      ,[Market]
      ,[RequestType]
      ,[ProcedureRequestType]
      ,[OpenByCategory]
      ,[LegalFrameworkName]
      ,[Duration]
      ,[DurationType]
      ,[DueDateForReceivingReplies]
      ,[OpeningRepliesDate]
      ,[EffectiveOpeningDate]
      ,[BusinessOperationState]
      ,[BusinessOperationName]
      ,[BusinessOperationCountry]
      ,[AllowAuction]
      ,[SuppliersInvited]
      ,[DirectSuppliersInvited]
      ,[ProcedureVisualizationCount]
      ,[SuppliersExpressedInterestCount]
      ,[RepliesCount]
      ,[ExternalRepliesCount]
      ,[CounterProposalRepliesCount]
      ,[DistinctSupplierWithReplies]
      ,[NumLotes]
      ,[ProcedureRequestDescription]
      ,[ProcedureRequestState]
      ,[ProcedureRequestStateId]
      ,[Awarded]
      ,[Award ID]
      ,[AwardDate]
      ,[AwardTotalPrice]
      ,[AwarderDisplayName]
      ,[SupplierName]
      ,[SupplierVat]
      ,[SupplierPhoneNumber]
      ,[SupplierEmailAddress]
      ,[DimMainCategoryCode]
      ,[DimMainCategoryTypeCode]
      ,[ProcedureRequestOpeningState]
      ,[TypeOfContract]
      ,[SubTypeOfContract]
      ,[AddicionalCategoryCodes]
      ,[Tipo]
      ,[CodigoProveedor]
      ,[ContractNoticeUniqueIdentifier]
      ,[Departamento Entidad]
      ,[Ciudad Entidad]
      ,[Departamento Proveedor]
      ,[Ciudad Proveedor]
      ,[Codigo Moneda]
      ,[NumeroAdendas]
      ,[AdtEditedAt]
      ,[OrdenEntidad]
      ,[Justificación Modalidad de Contratación]
      ,[Entidad Centralizada]
      ,[URLProceso]
  FROM [CCE_Reports].[SECOPII].[V_HistoricoProcedimientos]