SELECT TOP (1000) [HubCategorizationHashKey]
      ,[LoadDate]
      ,[RecordSource]
      ,[SatCategorizationHashDiff]
      ,[AuditIsVisible]
      ,[cdcstatus]
      ,[cdctimestamp]
      ,[CreateAppName]
      ,[CreateAuthor]
      ,[CreateCompanyCode]
      ,[CreateDate]
      ,[CreateSubstitute]
      ,[CreateSubstituteRole]
      ,[CreateTransactionId]
      ,[MetaModelUniqueName]
      ,[PersistOrder]
      ,[VersionAppName]
      ,[VersionAuthor]
      ,[VersionCompanyCode]
      ,[VersionDate]
      ,[VersionNumber]
      ,[VersionSubstitute]
      ,[VersionSubstituteRole]
      ,[VersionTransactionId]
      ,[Deleted]
  FROM [CCE_Sandbox].[datavault].[Sat_Categorization]